"""FacelessForge long-form YouTube uploader — 10 minute case study videos.

Pipeline:
  POST /api/longform/generate {companyName, industry, channelId, plan}
    -> OpenRouter: 10-min script with hooks (openrouter/free)
    -> B-roll from teaser-api _get_broll_clips() chain
    -> ffmpeg concat 10 clips * 60s = 600s, scale 1280x720, drawtext overlays
    -> upload to YouTube via google-api-python-client
    -> save project to Mongo

Auth: Uses get_current_user (JWT HS256, same secret as /api/auth/login).
Title/description/tags auto-generated by OpenRouter.
Thumbnail: optional Unsplash + drawtext (future).
"""
from __future__ import annotations

import logging
import os
import re
import subprocess
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional, List

from fastapi import APIRouter, Depends, HTTPException, Request
from pydantic import BaseModel, Field

from ..auth import get_current_user
from ..db import get_db

logger = logging.getLogger("facelessforge.longform")

router = APIRouter(prefix="/api/longform", tags=["longform"])

STORAGE_DIR = Path(os.environ.get("STORAGE_DIR", "/opt/facelessforge/storage"))
STORAGE_DIR.mkdir(parents=True, exist_ok=True)
R2_BUCKET = os.environ.get("R2_BUCKET", "facelessforge-prod")
R2_PUBLIC = os.environ.get("R2_PUBLIC_BASE_URL", os.environ.get("STORAGE_PUBLIC_BASE_URL", "https://videos.ethinx.solutions"))

OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY", "").strip()
TEASER_API_URL = os.environ.get("TEASER_API_URL", "http://host.docker.internal:8005").strip()
YOUTUBE_CLIENT_ID = os.environ.get("YOUTUBE_CLIENT_ID", "").strip()
YOUTUBE_CLIENT_SECRET = os.environ.get("YOUTUBE_CLIENT_SECRET", "").strip()
YOUTUBE_REFRESH_TOKEN = os.environ.get("YOUTUBE_REFRESH_TOKEN", "").strip()


def _now():
    return datetime.now(timezone.utc)


def _scrub(text: str, max_len: int = 80) -> str:
    if not text:
        return ""
    t = text.replace("\\", "\\\\").replace(":", "\\:").replace("'", "\\'").replace("\n", " ")
    return t[:max_len]


class LongformRequest(BaseModel):
    companyName: str = Field(..., min_length=1)
    industry: str = Field(default="Builder")
    channelId: Optional[str] = None
    plan: Optional[str] = None
    jobId: Optional[str] = None
    privacy: str = "public"  # public|private|unlisted
    duration_minutes: int = 10
    jobId: Optional[str] = None


class LongformResponse(BaseModel):
    jobId: str
    projectId: str
    script: Optional[str] = None
    videoPath: str
    publicUrl: str
    youtube: dict
    title: str
    description: str
    tags: List[str]
    status: str
    createdAt: str


@router.get("/health")
async def longform_health():
    return {
        "ok": True,
        "service": "facelessforge-longform",
        "openrouter": "SET" if OPENROUTER_API_KEY else "MISSING",
        "teaser_api": TEASER_API_URL,
        "youtube": {
            "client_configured": bool(YOUTUBE_CLIENT_ID and YOUTUBE_CLIENT_SECRET),
            "refresh_token_present": bool(YOUTUBE_REFRESH_TOKEN),
        },
        "storage": str(STORAGE_DIR),
        "r2_bucket": R2_BUCKET,
        "r2_public": R2_PUBLIC,
        "timestamp": _now().isoformat(),
    }


def _call_openrouter_10min(companyName: str, industry: str) -> dict:
    """Returns {title, description, tags, script} via openrouter/free."""
    if not OPENROUTER_API_KEY:
        logger.info("OPENROUTER_API_KEY not set, using static script")
        return {
            "title": f"{companyName} {industry} Empire Case Study | Faceless Forge",
            "description": f"How {companyName} scaled their {industry.lower()} empire using FacelessForge. Subscribe for more.",
            "tags": [industry.lower(), "case study", "faceless", "facelessforge", "ethinx"],
            "script": f"Welcome to Faceless Forge case studies. Today we look at {companyName}, a leading {industry.lower()} business. They scaled...",
        }
    try:
        import requests
        prompt = f"""You are a YouTube strategist. Generate a JSON object with keys: title (<=90 chars), description (<=500 chars, 1 paragraph + CTA + 5 hashtags), tags (10 tags), script (10 minute voiceover, ~1500 words, hook in first 30s, 5 chapters, ends with CTA to https://facelessforge.ethinx.solutions). Company: {companyName}. Industry: {industry}. Return only valid JSON, no markdown."""
        payload = {
            "model": "openrouter/free",
            "messages": [
                {"role": "system", "content": "You only respond with valid JSON."},
                {"role": "user", "content": prompt},
            ],
            "max_tokens": 2000,
            "temperature": 0.7,
        }
        headers = {
            "Authorization": f"Bearer {OPENROUTER_API_KEY}",
            "Content-Type": "application/json",
            "HTTP-Referer": "https://facelessforge.ethinx.solutions",
            "X-Title": "FacelessForge Longform",
        }
        for attempt in range(3):
            r = requests.post(
                "https://openrouter.ai/api/v1/chat/completions",
                json=payload, headers=headers, timeout=30,
            )
            logger.info(f"OPENROUTER longform attempt {attempt+1} status={r.status_code}")
            if r.status_code == 429:
                time.sleep(5)
                continue
            if r.status_code == 200:
                data = r.json()
                content = (data.get("choices", [{}])[0].get("message", {}).get("content") or "").strip()
                if content.startswith("```"):
                    content = re.sub(r"^```(?:json)?\s*", "", content)
                    content = re.sub(r"\s*```$", "", content)
                try:
                    import json
                    return json.loads(content)
                except Exception:
                    m = re.search(r"\{[\s\S]*\}", content)
                    if m:
                        return json.loads(m.group(0))
                    raise ValueError(f"OpenRouter returned non-JSON: {content[:200]}")
        return {
            "title": f"{companyName} {industry} Empire Case Study | Faceless Forge",
            "description": f"How {companyName} scaled their {industry.lower()} empire using FacelessForge. Subscribe for more.",
            "tags": [industry.lower(), "case study", "faceless", "facelessforge", "ethinx"],
            "script": f"Welcome to Faceless Forge case studies. Today we look at {companyName}, a leading {industry.lower()} business. They scaled...",
        }
    except Exception as e:
        logger.warning(f"OPENROUTER longform failed: {e}")
        return {
            "title": f"{companyName} {industry} Empire Case Study | Faceless Forge",
            "description": f"How {companyName} scaled their {industry.lower()} empire using FacelessForge. Subscribe for more.",
            "tags": [industry.lower(), "case study", "faceless", "facelessforge", "ethinx"],
            "script": f"Welcome to Faceless Forge case studies. Today we look at {companyName}, a leading {industry.lower()} business. They scaled...",
        }


def _get_broll_clips_via_teaser(industry: str, jobId: str) -> List[dict]:
    """Ask teaser-api to render the 10-min B-roll for us, returns [{path, source, duration}].
    Calls teaser-api POST /generate-longform-broll which uses the same _get_broll_clips chain.
    """
    try:
        import requests
        url = TEASER_API_URL.rstrip("/") + "/generate-longform-broll"
        r = requests.post(url, json={"industry": industry, "jobId": jobId, "clips": 10}, timeout=120)
        if r.status_code == 200:
            data = r.json()
            return data.get("clips", [])
    except Exception as e:
        logger.warning(f"teaser-api b-roll call failed: {e}")
    return []


def _render_longform(jobId: str, companyName: str, industry: str, script: str, clip_paths: List[str], target_seconds: int = 600) -> Path:
    """Concatenate clip_paths into ~target_seconds total, scale 1280x720, add drawtext overlays + audio track (silent if no voice)."""
    out_path = STORAGE_DIR / f"{jobId}.mp4"
    if out_path.exists():
        try:
            out_path.unlink()
        except Exception:
            pass
    font_bold = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
    company_e = _scrub(companyName.upper()[:40])
    industry_e = _scrub(f"{industry} • Adelaide"[:48])
    overlay_filter = (
        f"drawtext=fontfile={font_bold}:text='{company_e}':fontcolor=white:fontsize=72:x=(w-text_w)/2:y=(h-text_h)/2-100:box=1:boxcolor=black@0.55:boxborderw=18,"
        f"drawtext=fontfile={font_bold}:text='{industry_e}':fontcolor=#00E5FF:fontsize=42:x=(w-text_w)/2:y=(h-text_h)/2+10,"
        f"drawtext=fontfile={font_bold}:text='Case Study':fontcolor=white:fontsize=32:x=(w-text_w)/2:y=(h-text_h)/2+90"
    )
    if not clip_paths:
        # fallback: navy + noise + scale
        cmd = [
            "ffmpeg", "-y",
            "-f", "lavfi", "-i", f"color=c=0x0f172a:s=1280x720:r=30:d={target_seconds}",
            "-f", "lavfi", "-i", "anullsrc=r=44100:cl=stereo",
            "-vf", f"noise=alls=25:allf=t,{overlay_filter}",
            "-c:v", "libx264", "-pix_fmt", "yuv420p", "-b:v", "2000k", "-preset", "fast",
            "-c:a", "aac", "-shortest",
            str(out_path),
        ]
    else:
        # Build concat list
        list_file = STORAGE_DIR / f"{jobId}_list.txt"
        per_clip = max(5.0, target_seconds / len(clip_paths))
        with open(list_file, "w") as f:
            for cp in clip_paths:
                f.write(f"file '{cp}'\n")
                f.write(f"inpoint 0\n")
                f.write(f"outpoint {per_clip}\n")
        cmd = [
            "ffmpeg", "-y",
            "-f", "concat", "-safe", "0", "-i", str(list_file),
            "-f", "lavfi", "-i", "anullsrc=r=44100:cl=stereo",
            "-vf", f"scale=1280:720:force_original_aspect_ratio=decrease,pad=1280:720:(ow-iw)/2:(oh-ih)/2:black,setsar=1,{overlay_filter}",
            "-t", str(target_seconds),
            "-c:v", "libx264", "-pix_fmt", "yuv420p", "-b:v", "2000k", "-preset", "fast",
            "-c:a", "aac", "-shortest",
            str(out_path),
        ]
    logger.info(f"FFMPEG longform jobId={jobId} clips={len(clip_paths)} target={target_seconds}s")
    result = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=900)
    if not out_path.exists():
        raise RuntimeError(f"longform render failed: stderr={result.stderr.decode()[:500]}")
    return out_path


def _upload_to_youtube(path: Path, title: str, description: str, tags: List[str], privacy: str = "public", made_for_kids: bool = False) -> dict:
    """Upload to YouTube using OAuth refresh token. Returns {videoId, status, url, mock}."""
    if not (YOUTUBE_CLIENT_ID and YOUTUBE_CLIENT_SECRET and YOUTUBE_REFRESH_TOKEN):
        return {
            "videoId": None,
            "status": "mock",
            "url": None,
            "mock": True,
            "reason": "YOUTUBE_CLIENT_ID/SECRET/REFRESH_TOKEN not all set",
            "size_bytes": path.stat().st_size if path.exists() else 0,
        }
    try:
        from google.oauth2.credentials import Credentials
        from googleapiclient.discovery import build
        from googleapiclient.http import MediaFileUpload
        creds = Credentials(
            token=None,
            refresh_token=YOUTUBE_REFRESH_TOKEN,
            token_uri="https://oauth2.googleapis.com/token",
            client_id=YOUTUBE_CLIENT_ID,
            client_secret=YOUTUBE_CLIENT_SECRET,
            scopes=["https://www.googleapis.com/auth/youtube.upload", "https://www.googleapis.com/auth/youtube"],
        )
        youtube = build("youtube", "v3", credentials=creds, cache_discovery=False)
        body = {
            "snippet": {
                "title": title[:100],
                "description": description[:5000],
                "tags": tags[:15],
                "categoryId": "28",
            },
            "status": {
                "privacyStatus": privacy if privacy in ("public", "private", "unlisted") else "public",
                "selfDeclaredMadeForKids": made_for_kids,
            },
        }
        media = MediaFileUpload(str(path), mimetype="video/mp4", resumable=True)
        upload = youtube.videos().insert(part="snippet,status", body=body, media_body=media)
        response = None
        while response is None:
            status, response = upload.next_chunk()
        video_id = response.get("id")
        return {
            "videoId": video_id,
            "status": "uploaded",
            "url": f"https://youtu.be/{video_id}",
            "mock": False,
        }
    except Exception as e:
        logger.warning(f"YouTube upload failed: {e}")
        return {
            "videoId": None,
            "status": "failed",
            "error": str(e),
            "mock": True,
            "size_bytes": path.stat().st_size if path.exists() else 0,
        }


@router.post("/generate", response_model=LongformResponse)
async def longform_generate(req: LongformRequest, request: Request, user=Depends(get_current_user)):
    """Generate a 10-min case study video and (optionally) upload to YouTube.

    Auth: standard JWT (Bearer). Channel ID is taken from req or user record.
    Returns: projectId, videoPath, publicUrl (R2 after upload), youtube status.
    """
    jobId = (req.jobId or "").strip() or uuid.uuid4().hex[:10]
    projectId = f"longform_{jobId}"
    companyName = req.companyName.strip()
    industry = (req.industry or "Builder").strip()
    user_id = user.get("id") or user.get("user_id")
    user_email = user.get("email")

    # 1. OpenRouter: 10-min script + title/desc/tags
    meta = _call_openrouter_10min(companyName, industry)
    title = meta.get("title", f"{companyName} {industry} Case Study")
    description = meta.get("description", "")
    tags = meta.get("tags", [industry.lower(), "case study"])
    script = meta.get("script", "")

    # 2. Get B-roll from teaser-api
    clips = _get_broll_clips_via_teaser(industry, jobId)
    clip_paths = [c.get("path") for c in clips if c.get("path") and Path(c["path"]).exists()]
    # 3. Render 10 min
    target_seconds = max(60, req.duration_minutes * 60)
    out_path = _render_longform(jobId, companyName, industry, script, clip_paths, target_seconds=target_seconds)

    # 4. Upload to YouTube (or mock)
    yt = _upload_to_youtube(out_path, title, description, tags, privacy=req.privacy)

    # 5. Persist project
    public_path = str(out_path)
    public_url = f"{R2_PUBLIC}/longform/{jobId}.mp4" if R2_PUBLIC else ""
    project = {
        "id": projectId,
        "jobId": jobId,
        "user_id": user_id,
        "email": user_email,
        "companyName": companyName,
        "industry": industry,
        "channelId": req.channelId or user.get("channel_id"),
        "title": title,
        "description": description,
        "tags": tags,
        "script": script[:10000] if script else "",
        "videoPath": public_path,
        "publicUrl": public_url,
        "youtube": yt,
        "privacy": req.privacy,
        "duration": target_seconds,
        "size": out_path.stat().st_size if out_path.exists() else 0,
        "created_at": _now().isoformat(),
    }
    try:
        db = get_db()
        await db.longform_projects.update_one(
            {"id": projectId},
            {"$set": project, "$setOnInsert": {"created_at": _now().isoformat()}},
            upsert=True,
        )
    except Exception as e:
        logger.warning(f"persist longform project failed: {e}")

    return LongformResponse(
        jobId=jobId,
        projectId=projectId,
        script=script[:2000] if script else None,
        videoPath=public_path,
        publicUrl=public_url,
        youtube=yt,
        title=title,
        description=description,
        tags=tags,
        status="completed",
        createdAt=project["created_at"],
    )
